- name: Sync code
  synchronize:
    src: "../../../"
    dest: "{{ gradle_project_path }}/"
    delete: Yes
    rsync_opts:
      - "--exclude=.git/"
      - "--exclude-from=.gitignore"
      - "--delete-excluded"
  when: gradle_project_path != '.'

- name: Build project
  shell: |
    set -e
    cd "{{ gradle_project_path }}"
    {{ gradle_bin }} {{ gradle_project_task}}
