---
- name: BBuddy Server
  hosts: all
  any_errors_fatal: true
  roles:
    - gradle
    - role: mysql
      mysql:
        database: bbuddytest
        user: nerd
        password: dbs3cr3t
    - firefox

- name: BBuddy CI
  hosts: bbuddy_ci_servers
  any_errors_fatal: true
  roles:
    - role: jenkins
      jenkins:
        port: 8000
