- name: Gradle | Ensure unzip
  package: name=unzip
  become: Yes

- name: Gradle | Ensure install directory
  file: path="{{ gradle_home | dirname }}" state=directory
  become: Yes

- name: Gradle | Ensure gradle
  unarchive:
    copy: false
    src: "https://services.gradle.org/distributions/gradle-{{gradle_version}}-all.zip"
    dest: "{{ gradle_home | dirname }}"
    creates: "{{ gradle_bin }}"
  become: Yes

- name: Gradle | Add the Gradle binary to the system path
  copy:
    dest: "{{ gradle_profile }}"
    content: |
      export GRADLE_HOME="{{ gradle_home }}"
      export PATH="$GRADLE_HOME/bin:$PATH"
  become: Yes
