- block:
    - name: Ensure Xvfb package
      apt: name="{{ item }}"
      with_items:
        - xserver-xorg-core
        - xvfb

    - name: Xvfb:{{ xvfb.display }} init.d script
      template: src=init_xvfb.sh.j2 dest=/etc/init.d/xvfb mode="0755"

    - name: Xvfb:{{ xvfb.display }} profile
      copy:
        dest: /etc/profile.d/xvfb.sh
        content: |
          export DISPLAY="${DISPLAY:-:{{ xvfb.display }}}"

  become: Yes
  when: ansible_os_family == "Debian"
