---
- block:
    - name: Obtain JDK
      unarchive: >
        src="{{ jdk8.download_url }}" remote_src=true
        dest="{{ jdk8.home | dirname }}"
        creates="{{ jdk8.home }}/bin/java"

    - name: JDK profile
      copy:
        dest: "{{ jdk8.profile }}"
        content: |
          export JAVA_HOME="{{ jdk8.home }}"
          export JRE_HOME="${JAVA_HOME}/jre"
          export DERBY_HOME="${JAVA_HOME}/db"
          export PATH="$PATH:$JAVA_HOME/bin:${DERBY_HOME}/bin:${JRE_HOME}/bin"
          export J2SDKDIR="${JAVA_HOME}"
          export J2REDIR="${JRE_HOME}"

  become: Yes
  when: ansible_os_family == "Debian"

